### PR TITLE
Fix/body scroll

### PR DESCRIPTION
**Pull request by koolamusic**
### Body Scroll Lock
- In response to issue #4 I have written some fixes to manage all of that effect. please check through and give feedback.

Thanks.

### CODE REVIEW

**Comment by neosiae** [comment]
Could you add a prop so users can choose whether or not they want body scroll lock.

Tests are more than welcome, you can test body to see if `overflowY` is hidden or not.

 Everything else is ok.

**Comment by neosiae** [comment]
Hey @koolamusic, will you be able to finish this?

**Comment by koolamusic** [comment]
- Any ideas on what to name the prop, I'd appreciate that. 
- With Docs, I'm cool.

**Comment by koolamusic** [comment]
In any other case, I would really appreciate any assistance I can get in completing this task. honestly

**Comment by neosiae** [comment]
What about `lockBodyAfterOpen`? Do you have a better suggestion?

That's it. Just add prop and document it. If you need any help, let me know.

**Comment by neosiae** [comment]
Maybe `lockBodyAfterOpen`?

That's it. Just add prop and document it. If you need any help, let me know.

**Comment by neosiae** [comment]
Hey @koolamusic, what is happening with this PR?

**Comment by koolamusic** [comment]
X

**Comment by koolamusic** [comment]
WIP

**Comment by neosiae** [comment]
@koolamusic Any updates?

**Comment by neosiae** [comment]
@koolamusic Will you finish this PR?

**Comment by neosiae** [comment]
@koolamusic Any updates on this?

**Comment by koolamusic** [comment]
Yeah, I'll send a PR in 24hrs, being caught at work

**Comment by neosiae** [comment]
@koolamusic Let me know if you want to finish this PR.

**Comment by neosiae** [comment]
@koolamusic Let me know if you are able to finish this PR.

**Comment by koolamusic** [comment]
:( my bad

**Pull request merged**
